class ModulationType:
    NONE = 0
    MODWHEEL = 1
    BEND_UP = 2
    BEND_DOWN = 3
    AFTERTOUCH = 4
    VELOCITY = 5 
    BIPOLAR_VELOCITY = 6 
    OFF_VELOCITY = 7
    KEYBOARD = 8 
    LFO1 = 9 
    LFO2 = 10
    AMP_ENV = 11
    FILTER ENV = 12
    AUX ENV  = 13
    MIDI_CTRL = 14
    Q-LINK1 = 15
    Q-LINK2 = 16 
    Q-LINK3 = 17
    Q-LINK4 = 18
    Q-LINK5 = 19
    Q-LINK6 = 20
    Q-LINK7 = 21
    Q-LINK8 = 22
    MODWHEEL = 23
    BEND UP = 24
    BEND DOWN = 25
    Q-LINK1_NOTE = 26
    Q-LINK2_NOTE = 27
    Q-LINK3_NOTE = 28
    Q-LINK4_NOTE = 29
    Q-LINK5_NOTE = 30
    Q-LINK6_NOTE = 31
    Q-LINK7_NOTE = 32
    Q-LINK8_NOTE = 33
    LFO1_NOTE_NOTE = 34
    LFO2_NOTE = 35
    MIDI_CTRL_NOTE = 36

class ProgramTemperamentTemplatesType:
    USER = 0
    EVEN_TEMPERED = 1
    ORCHESTRAL = 2
    WERKMEISTER = 3
    ONE_FIFTH_MEANTONE = 4
    ONE_FOURTH_MEANTONE = 5
    JUST = 6
    ARABIAN = 7
