from base import *
from envelopewidget import *
from filechooser import *
from hitbox import *
from keygroupdetails import *
from keygroupeditor import *
from keygroupeditorwindow import * #this is the newer one w/ custom widgets
from keygroupenvelope import *
from keygroupfilter import *
from lcdscreen import *
from multifxeditor import *
from programeditor import *
from programdetails import *
from programseditor import *
from recorddialog import *
from zoneeditor import *
#from mpcpadeditor import *
from widget import *
from rangewidget import *